---
- name: Configure access VLANs
  hosts: access_switches        # <- don't use 'all' unless you mean it
  gather_facts: false

  collections:
    - cisco.ios                 # this matches the ios_config module

  vars_prompt:
    - name: username
      prompt: "Username?"
      private: no
    - name: password
      prompt: "Password?"
      private: yes

  vars:
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"
    ansible_connection: network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable

  tasks:
    - name: Configure access VLANs from host vars in inventory
      cisco.ios.ios_config:
        parents: "interface {{ int_prefix | default('Gi1/0/') }}{{ item.1 }}"
        lines:
          - "switchport mode access"
          - "switchport access vlan {{ item.0.vlan }}"
          - "spanning-tree portfast"
      loop: "{{ access_sets | default([]) | subelements('ports') }}"
      when: access_sets is defined
